# With Dockerfile
# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python#runtime_config
runtime: custom
env: flex
service: streamlit-101

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
 
runtime_config:
  # You can also specify 2 for Python 2.7
  # python_version: 3
  operating_system: "ubuntu22"
  runtime_version: "3.9"

# The number of running instances may drop below this value for a short period of time during some events. If your application requires running continuously on a certain number of instances, consider overprovisioning.
# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python#:~:text=to%20the%20service.-,Note%3A%20The%20number%20of%20running%20instances%20may%20drop%20below%20this%20value%20for%20a%20short%20period%20of%20time%20during%20some%20events.%20If%20your%20application%20requires%20running%20continuously%20on%20a%20certain%20number%20of%20instances%2C%20consider%20overprovisioning.,-Defining%20environment%20variables
# manual_scaling:
#   instances: 1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
  target_concurrent_requests: 100

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# instance_class: B2
network:
  name: log-vpc
  subnetwork_name: log-vpc
  session_affinity: true
  forwarded_ports:
    - 8501:8080

# liveness_check:
#   path: "/liveness_check"
#   check_interval_sec: 30
#   timeout_sec: 4
#   failure_threshold: 3
#   success_threshold: 3

# readiness_check:
#   path: "/readiness_check"
#   check_interval_sec: 5
#   timeout_sec: 4
#   failure_threshold: 3
#   success_threshold: 3
#   app_start_timeout_sec: 300
